// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHniINh67D_qXjDaV0YzfqIgZFALVKVH8',
    appId: '1:572772243457:web:282e9b933ae8c0d854c800',
    messagingSenderId: '572772243457',
    projectId: 'fitfitmeal',
    authDomain: 'fitfitmeal.firebaseapp.com',
    storageBucket: 'fitfitmeal.appspot.com',
    measurementId: 'G-FGKMCT04Y0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASXSnd_p6l0JjERNnOp1M0SN87-4RY0b0',
    appId: '1:572772243457:android:06fd8c7d2db677a354c800',
    messagingSenderId: '572772243457',
    projectId: 'fitfitmeal',
    storageBucket: 'fitfitmeal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjJqR1N8ODdbJgz_DTarcQTpCjN5426ko',
    appId: '1:572772243457:ios:3e730c463b3f516854c800',
    messagingSenderId: '572772243457',
    projectId: 'fitfitmeal',
    storageBucket: 'fitfitmeal.appspot.com',
    iosClientId: '572772243457-32gughj64drmri037mtnspt6maj0k0j8.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitFitMeal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjJqR1N8ODdbJgz_DTarcQTpCjN5426ko',
    appId: '1:572772243457:ios:3e730c463b3f516854c800',
    messagingSenderId: '572772243457',
    projectId: 'fitfitmeal',
    storageBucket: 'fitfitmeal.appspot.com',
    iosClientId: '572772243457-32gughj64drmri037mtnspt6maj0k0j8.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitFitMeal',
  );
}
